### ISSUE TITLE
Add the default values

### ISSUE THREAD

**Issue by notgiorgi** [vhpoet/react-native-styling-cheat-sheet#4]
Default values for properties would be helpful.

I can send a PR

**Comment by vhpoet** [comment]
@notgiorgi a PR would be lovely!

**Comment by notgiorgi** [comment]
Any leads on that, cannot find any resource with list of properties and stuff

**Comment by vhpoet** [comment]
@notgiorgi not really, I thought you have an idea.

**Comment by notgiorgi** [comment]
@vhpoet 

I think this is it: https://facebook.github.io/yoga/docs/learn-more/

**Comment by vhpoet** [comment]
merged your PR, thank you!
